<?php
/**
 * Created by PhpStorm.
 * User: medar
 * Date: 30/11/2018
 * Time: 23:14
 */

namespace Drupal\jir_rest_api\Normalizer;


use Drupal;
use Drupal\serialization\Normalizer\EntityReferenceFieldItemNormalizer;

class EntityReferenceNormalizer extends EntityReferenceFieldItemNormalizer {

    public function normalize($field_item, $format = NULL, array $context = [])
    {
        Drupal::logger('jix_rest_api')->info('EntityReferenceNormalizer called at ' . date("d-m-Y H:i:s"));
        return parent::normalize($field_item, $format, $context); // TODO: Change the autogenerated stub
    }

}